
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gawlzxdwkhfvfqoaqvao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdhd2x6eGR3a2hmdmZxb2FxdmFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0Mjk4MjcsImV4cCI6MjA2MDAwNTgyN30.pToBS_O0gn90fS3S62K4z2EtB8OW2QJYtptfX7KTSnQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
